package sigmaBot.callBack;

public enum CallBackName {

    ADMIN("ADMIN"), CLIENT("CLIENT"), CLIENT_JOIN("CLIENT_JOIN"),
    CLIENT_MAIN_MENU("CLIENT_MAIN_MENU"), CLIENT_VVOD_PARAM("CLIENT_VVOD_PARAM"),
    CLIENT_GENERATE("CLIENT_GENERATE"), CLIENT_PROSM_PROG("CLIENT_PROSM_PROG"),
    PROSM_VSE_PROG("PROSM_VSE_PROG"), CLIENT_NABOR("CLIENT_NABOR"), CLIENT_XUDOI("CLIENT_XUDOI"),
    CLIENT_CHOISE("CLIENT_CHOISE"), CLIENT_SEND_CHOICE("CLIENT_SEND_CHOICE"),
    PROSM_CURRENT_PARAM("PROSM_CURRENT_PARAM"),
    TRAINER("TRAINER"),
    TRAINER_JOIN("TRAINER_JOIN"), TRAINER_REDACT("TRAINER_REDACT"),
    TRAINER_GET_CLIENT_CURRENT_PROG("TRAINER_GET_CLIENT_CURRENT_PROG"),
    YES_REDACT("YES_REDACT"), NO_REDACT("NO_REDACT"),
    TRAINER_ADD_EXERCISES("TRAINER_ADD_EXERCISES"),
    TRAINER_SEND_ADD_EXERCISES("TRAINER_SEND_ADD_EXERCISES"),
    CLIENT_REGISTRATION("CLIENT_REGISTRATION");
    private String callBackName;
     CallBackName(String commandName){
        this.callBackName = commandName;
    }

    public String getCallBackName() {
        return callBackName;
    }
}
